files = ["files/latex.tex", "files/include.tex"]
cmd = [
    ["pdflatex.exe",
        "-synctex=0",
        "-quiet",
        "-interaction=nonstopmode",
        "-output-directory={{.root}}",
        "-include-directory={{.root}}",
        "-job-name={{.name}}",
    "{{index .files 0}}"],
    ["powershell.exe",
        "-noprofile",
        "-command",
        '& {remove-item {{.root}}\* -include *.aux, *.gz, *.log}']
    ]


[[version]]
    name = "FunnySadDraft"
    [version.tags]
        funny = true
        sad = true
        draft = true


[[version]]
    name = "SadFinal"
    [version.tags]
        sad = true
        final = true